from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from urllib.parse import urlparse
from xml.etree import ElementTree as ET


def generate_jmeter_plan(
    contract_analysis: dict[str, Any],
    test_data: dict[str, Any],
    strategy: dict[str, Any],
    target_url: str,
    output_path: Path,
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    parsed = urlparse(target_url)
    load = strategy.get("load", {})
    users = str(load.get("users", 25))
    ramp = str(load.get("ramp_up_seconds", 10))
    duration = str(load.get("duration_seconds", 60))

    root = ET.Element("jmeterTestPlan", version="1.2", properties="5.0", jmeter="5.6.3")
    test_plan = ET.SubElement(root, "TestPlan", guiclass="TestPlanGui", testclass="TestPlan", testname="PerfAgent Test Plan", enabled="true")
    ET.SubElement(test_plan, "stringProp", name="TestPlan.comments").text = "Generated by PerfAgent AI"
    ET.SubElement(root, "hashTree")

    thread_group = ET.SubElement(root, "ThreadGroup", guiclass="ThreadGroupGui", testclass="ThreadGroup", testname="PerfAgent Load Thread Group", enabled="true")
    ET.SubElement(thread_group, "stringProp", name="ThreadGroup.num_threads").text = users
    ET.SubElement(thread_group, "stringProp", name="ThreadGroup.ramp_time").text = ramp
    ET.SubElement(thread_group, "stringProp", name="ThreadGroup.duration").text = duration
    ET.SubElement(thread_group, "boolProp", name="ThreadGroup.scheduler").text = "true"
    samplers = ET.SubElement(root, "hashTree")

    for item in test_data.get("endpoints", []):
        sampler = ET.SubElement(
            samplers,
            "HTTPSamplerProxy",
            guiclass="HttpTestSampleGui",
            testclass="HTTPSamplerProxy",
            testname=item["operation_id"],
            enabled="true",
        )
        ET.SubElement(sampler, "stringProp", name="HTTPSampler.domain").text = parsed.hostname or ""
        ET.SubElement(sampler, "stringProp", name="HTTPSampler.port").text = str(parsed.port or _default_port(parsed.scheme))
        ET.SubElement(sampler, "stringProp", name="HTTPSampler.protocol").text = parsed.scheme or "http"
        ET.SubElement(sampler, "stringProp", name="HTTPSampler.path").text = _apply_path_params(item["path"], item.get("path_params", {}))
        ET.SubElement(sampler, "stringProp", name="HTTPSampler.method").text = item["method"]
        if item.get("body") is not None:
            ET.SubElement(sampler, "stringProp", name="Argument.value").text = json.dumps(item["body"])
        ET.SubElement(samplers, "hashTree")

    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    tree.write(output_path, encoding="unicode", xml_declaration=True)
    return output_path


def _default_port(scheme: str) -> int:
    return 443 if scheme == "https" else 80


def _apply_path_params(path: str, params: dict[str, Any]) -> str:
    for name, value in params.items():
        path = path.replace("{" + name + "}", str(value))
    return path
