import json
import os
from hybrid_rag import run_hybrid_rag

def load_queries(file_path):
    with open(file_path, 'r') as f:
        return json.load(f)

def generate_report(queries, output_path):
    results = []
    print(f"Starting report generation for {len(queries)} queries...")
    
    for i, item in enumerate(queries):
        query_text = item['query']
        print(f"[{i+1}/{len(queries)}] Processing query: {query_text[:50]}...")
        
        try:
            # Attempt to run the hybrid RAG
            # If GROQ_API_KEY is missing/invalid, this might fail
            response = run_hybrid_rag(query_text)
            answer = response.get("answer", "No answer generated.")
            route = response.get("route", "unknown")
        except Exception as e:
            print(f"  Error processing query: {e}")
            answer = f"Error: {str(e)}"
            route = "failed"
        
        results.append({
            "query": query_text,
            "route": route,
            "answer": answer,
            "analysis": item.get("why_graphrag_is_useful", "N/A")
        })

    print(f"Writing report to {output_path}...")
    with open(output_path, 'w') as f:
        f.write("# Week 2 RAG Comparison Report\n\n")
        f.write("This report compares the routing decisions and answers generated by the Hybrid RAG system for a set of evaluation queries.\n\n")
        
        f.write("| ID | Query | Route | Answer | Why this route? |\n")
        f.write("|---|---|---|---|---|\n")
        
        for i, res in enumerate(results):
            # Escaping pipe characters in Markdown table
            q = res['query'].replace('|', r'\|')
            a = res['answer'].replace('|', r'\|').replace('\n', ' ')
            r = res['route']
            analysis = res['analysis'].replace('|', r'\|')
            
            f.write(f"| {i+1} | {q} | **{r}** | {a} | {analysis} |\n")
            
        f.write("\n\n## Detailed Analysis\n\n")
        for i, res in enumerate(results):
            f.write(f"### Query {i+1}: {res['query']}\n")
            f.write(f"- **Route Taken:** `{res['route']}`\n")
            f.write(f"- **Expected Value of Graph:** {res['analysis']}\n")
            f.write(f"- **Final Answer:**\n\n{res['answer']}\n\n")
            f.write("---\n\n")

    print("Report generation complete.")

if __name__ == "__main__":
    # Ensure we are in the right directory or use absolute paths
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    queries_path = os.path.join(base_dir, "evaluation", "comparison_queries.json")
    output_path = os.path.join(base_dir, "evaluation", "comparison_results.md")
    
    queries = load_queries(queries_path)
    generate_report(queries, output_path)
